#ifndef GAMENETWORK_NETWORK_CLIENT_ADAPTER_ICLIENTCONNECTIONCALLBACK_H_
#define GAMENETWORK_NETWORK_CLIENT_ADAPTER_ICLIENTCONNECTIONCALLBACK_H_
struct IClientConnectionCallback {
  virtual void OnConnect(bool success) = 0;
  virtual void OnDisconnect() = 0;
};
#endif //GAMENETWORK_NETWORK_CLIENT_ADAPTER_ICLIENTCONNECTIONCALLBACK_H_
